/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWikiRouteImport } from './routes/_layout/wiki'
import { Route as LayoutToolsRouteImport } from './routes/_layout/tools'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRosterRouteImport } from './routes/_layout/roster'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutGuildWarRouteImport } from './routes/_layout/guild-war'
import { Route as LayoutGalleryRouteImport } from './routes/_layout/gallery'
import { Route as LayoutEventsRouteImport } from './routes/_layout/events'
import { Route as LayoutDesignSystemPreviewRouteImport } from './routes/_layout/design-system-preview'
import { Route as LayoutAnnouncementsRouteImport } from './routes/_layout/announcements'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutToolsIndexRouteImport } from './routes/_layout/tools/index'
import { Route as LayoutToolsWarAnalyticsRouteImport } from './routes/_layout/tools/war-analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWikiRoute = LayoutWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsRoute = LayoutToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRosterRoute = LayoutRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGuildWarRoute = LayoutGuildWarRouteImport.update({
  id: '/guild-war',
  path: '/guild-war',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGalleryRoute = LayoutGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsRoute = LayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDesignSystemPreviewRoute =
  LayoutDesignSystemPreviewRouteImport.update({
    id: '/design-system-preview',
    path: '/design-system-preview',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAnnouncementsRoute = LayoutAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsIndexRoute = LayoutToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutToolsRoute,
} as any)
const LayoutToolsWarAnalyticsRoute = LayoutToolsWarAnalyticsRouteImport.update({
  id: '/war-analytics',
  path: '/war-analytics',
  getParentRoute: () => LayoutToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/announcements': typeof LayoutAnnouncementsRoute
  '/design-system-preview': typeof LayoutDesignSystemPreviewRoute
  '/events': typeof LayoutEventsRoute
  '/gallery': typeof LayoutGalleryRoute
  '/guild-war': typeof LayoutGuildWarRoute
  '/profile': typeof LayoutProfileRoute
  '/roster': typeof LayoutRosterRoute
  '/settings': typeof LayoutSettingsRoute
  '/tools': typeof LayoutToolsRouteWithChildren
  '/wiki': typeof LayoutWikiRoute
  '/tools/war-analytics': typeof LayoutToolsWarAnalyticsRoute
  '/tools/': typeof LayoutToolsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/announcements': typeof LayoutAnnouncementsRoute
  '/design-system-preview': typeof LayoutDesignSystemPreviewRoute
  '/events': typeof LayoutEventsRoute
  '/gallery': typeof LayoutGalleryRoute
  '/guild-war': typeof LayoutGuildWarRoute
  '/profile': typeof LayoutProfileRoute
  '/roster': typeof LayoutRosterRoute
  '/settings': typeof LayoutSettingsRoute
  '/wiki': typeof LayoutWikiRoute
  '/': typeof LayoutIndexRoute
  '/tools/war-analytics': typeof LayoutToolsWarAnalyticsRoute
  '/tools': typeof LayoutToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/announcements': typeof LayoutAnnouncementsRoute
  '/_layout/design-system-preview': typeof LayoutDesignSystemPreviewRoute
  '/_layout/events': typeof LayoutEventsRoute
  '/_layout/gallery': typeof LayoutGalleryRoute
  '/_layout/guild-war': typeof LayoutGuildWarRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/roster': typeof LayoutRosterRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tools': typeof LayoutToolsRouteWithChildren
  '/_layout/wiki': typeof LayoutWikiRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/tools/war-analytics': typeof LayoutToolsWarAnalyticsRoute
  '/_layout/tools/': typeof LayoutToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/announcements'
    | '/design-system-preview'
    | '/events'
    | '/gallery'
    | '/guild-war'
    | '/profile'
    | '/roster'
    | '/settings'
    | '/tools'
    | '/wiki'
    | '/tools/war-analytics'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/announcements'
    | '/design-system-preview'
    | '/events'
    | '/gallery'
    | '/guild-war'
    | '/profile'
    | '/roster'
    | '/settings'
    | '/wiki'
    | '/'
    | '/tools/war-analytics'
    | '/tools'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/admin'
    | '/_layout/announcements'
    | '/_layout/design-system-preview'
    | '/_layout/events'
    | '/_layout/gallery'
    | '/_layout/guild-war'
    | '/_layout/profile'
    | '/_layout/roster'
    | '/_layout/settings'
    | '/_layout/tools'
    | '/_layout/wiki'
    | '/_layout/'
    | '/_layout/tools/war-analytics'
    | '/_layout/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wiki': {
      id: '/_layout/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof LayoutWikiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools': {
      id: '/_layout/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof LayoutToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/roster': {
      id: '/_layout/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof LayoutRosterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/guild-war': {
      id: '/_layout/guild-war'
      path: '/guild-war'
      fullPath: '/guild-war'
      preLoaderRoute: typeof LayoutGuildWarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/gallery': {
      id: '/_layout/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof LayoutGalleryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events': {
      id: '/_layout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof LayoutEventsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/design-system-preview': {
      id: '/_layout/design-system-preview'
      path: '/design-system-preview'
      fullPath: '/design-system-preview'
      preLoaderRoute: typeof LayoutDesignSystemPreviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/announcements': {
      id: '/_layout/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof LayoutAnnouncementsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools/': {
      id: '/_layout/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof LayoutToolsIndexRouteImport
      parentRoute: typeof LayoutToolsRoute
    }
    '/_layout/tools/war-analytics': {
      id: '/_layout/tools/war-analytics'
      path: '/war-analytics'
      fullPath: '/tools/war-analytics'
      preLoaderRoute: typeof LayoutToolsWarAnalyticsRouteImport
      parentRoute: typeof LayoutToolsRoute
    }
  }
}

interface LayoutToolsRouteChildren {
  LayoutToolsWarAnalyticsRoute: typeof LayoutToolsWarAnalyticsRoute
  LayoutToolsIndexRoute: typeof LayoutToolsIndexRoute
}

const LayoutToolsRouteChildren: LayoutToolsRouteChildren = {
  LayoutToolsWarAnalyticsRoute: LayoutToolsWarAnalyticsRoute,
  LayoutToolsIndexRoute: LayoutToolsIndexRoute,
}

const LayoutToolsRouteWithChildren = LayoutToolsRoute._addFileChildren(
  LayoutToolsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAnnouncementsRoute: typeof LayoutAnnouncementsRoute
  LayoutDesignSystemPreviewRoute: typeof LayoutDesignSystemPreviewRoute
  LayoutEventsRoute: typeof LayoutEventsRoute
  LayoutGalleryRoute: typeof LayoutGalleryRoute
  LayoutGuildWarRoute: typeof LayoutGuildWarRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutRosterRoute: typeof LayoutRosterRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutToolsRoute: typeof LayoutToolsRouteWithChildren
  LayoutWikiRoute: typeof LayoutWikiRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAnnouncementsRoute: LayoutAnnouncementsRoute,
  LayoutDesignSystemPreviewRoute: LayoutDesignSystemPreviewRoute,
  LayoutEventsRoute: LayoutEventsRoute,
  LayoutGalleryRoute: LayoutGalleryRoute,
  LayoutGuildWarRoute: LayoutGuildWarRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutRosterRoute: LayoutRosterRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutToolsRoute: LayoutToolsRouteWithChildren,
  LayoutWikiRoute: LayoutWikiRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
