import { beforeAll, beforeEach, describe, expect, it } from 'vitest';
import i18next from 'i18next';
import {
  formatLargeNumber,
  formatPercentage,
  formatWarDate,
  generateAnalyticsSnapshot,
} from '@/features/GuildWar/components/WarAnalytics/utils';

describe('WarAnalytics utils localization', () => {
  beforeAll(async () => {
    if (!i18next.isInitialized) {
      await i18next.init({
        lng: 'en',
        fallbackLng: 'en',
        debug: false,
        showSupportNotice: false,
        interpolation: { escapeValue: false },
        resources: {
          en: {
            translation: {
              common: {
                unknown: 'N/A',
              },
              guild_war: {
                analytics_mode_compare: 'Compare',
                analytics_mode_rankings: 'Rankings',
                analytics_mode_teams: 'Teams',
                analytics_metric_damage: 'Damage',
                analytics_snapshot_title: 'War Analytics Snapshot',
                analytics_snapshot_date_range: 'Date range: {{start}} to {{end}}',
                analytics_snapshot_wars_analyzed: 'Wars analyzed: {{count}}',
                analytics_snapshot_mode: 'Mode: {{mode}}',
                analytics_snapshot_metric: 'Metric: {{metric}}',
                analytics_snapshot_compare_members: 'Comparing {{count}} members',
                analytics_snapshot_top_by_metric: 'Top {{count}} by {{metric}}:',
                analytics_snapshot_member_line: '{{rank}}. {{username}}: {{value}}',
                analytics_snapshot_ranking_line: '{{rank}}. {{username}} ({{className}}): {{value}}',
                analytics_snapshot_generated_by: 'Generated by Guild Management System',
              },
            },
          },
          'zh-CN': {
            translation: {
              common: {
                unknown: '未知',
              },
              guild_war: {
                analytics_mode_compare: '对比',
                analytics_mode_rankings: '排行',
                analytics_mode_teams: '队伍',
                analytics_metric_damage: '伤害',
                analytics_snapshot_title: '公会战分析快照',
                analytics_snapshot_date_range: '时间范围：{{start}} 至 {{end}}',
                analytics_snapshot_wars_analyzed: '分析战斗数：{{count}}',
                analytics_snapshot_mode: '模式：{{mode}}',
                analytics_snapshot_metric: '指标：{{metric}}',
                analytics_snapshot_compare_members: '对比成员数：{{count}}',
                analytics_snapshot_top_by_metric: '{{metric}} 前 {{count}} 名：',
                analytics_snapshot_member_line: '{{rank}}. {{username}}：{{value}}',
                analytics_snapshot_ranking_line: '{{rank}}. {{username}}（{{className}}）：{{value}}',
                analytics_snapshot_generated_by: '由公会管理系统生成',
              },
            },
          },
        },
      });
      return;
    }

    i18next.addResourceBundle('en', 'translation', { common: { unknown: 'N/A' } }, true, true);
    i18next.addResourceBundle(
      'en',
      'translation',
      {
        guild_war: {
          analytics_mode_compare: 'Compare',
          analytics_mode_rankings: 'Rankings',
          analytics_mode_teams: 'Teams',
          analytics_metric_damage: 'Damage',
          analytics_snapshot_title: 'War Analytics Snapshot',
          analytics_snapshot_date_range: 'Date range: {{start}} to {{end}}',
          analytics_snapshot_wars_analyzed: 'Wars analyzed: {{count}}',
          analytics_snapshot_mode: 'Mode: {{mode}}',
          analytics_snapshot_metric: 'Metric: {{metric}}',
          analytics_snapshot_compare_members: 'Comparing {{count}} members',
          analytics_snapshot_top_by_metric: 'Top {{count}} by {{metric}}:',
          analytics_snapshot_member_line: '{{rank}}. {{username}}: {{value}}',
          analytics_snapshot_ranking_line: '{{rank}}. {{username}} ({{className}}): {{value}}',
          analytics_snapshot_generated_by: 'Generated by Guild Management System',
        },
      },
      true,
      true
    );
    i18next.addResourceBundle('zh-CN', 'translation', { common: { unknown: '未知' } }, true, true);
    i18next.addResourceBundle(
      'zh-CN',
      'translation',
      {
        guild_war: {
          analytics_mode_compare: '对比',
          analytics_mode_rankings: '排行',
          analytics_mode_teams: '队伍',
          analytics_metric_damage: '伤害',
          analytics_snapshot_title: '公会战分析快照',
          analytics_snapshot_date_range: '时间范围：{{start}} 至 {{end}}',
          analytics_snapshot_wars_analyzed: '分析战斗数：{{count}}',
          analytics_snapshot_mode: '模式：{{mode}}',
          analytics_snapshot_metric: '指标：{{metric}}',
          analytics_snapshot_compare_members: '对比成员数：{{count}}',
          analytics_snapshot_top_by_metric: '{{metric}} 前 {{count}} 名：',
          analytics_snapshot_member_line: '{{rank}}. {{username}}：{{value}}',
          analytics_snapshot_ranking_line: '{{rank}}. {{username}}（{{className}}）：{{value}}',
          analytics_snapshot_generated_by: '由公会管理系统生成',
        },
      },
      true,
      true
    );
  });

  beforeEach(async () => {
    await i18next.changeLanguage('en');
  });

  it('generates localized snapshot text in English', () => {
    const text = generateAnalyticsSnapshot(
      'compare',
      'damage',
      [{ war_id: 1, war_date: '2026-02-01T00:00:00.000Z', title: 'War 1' } as any],
      {
        members: [{ username: 'Alice', total_damage: 1234 }],
      }
    );

    expect(text).toContain('War Analytics Snapshot');
    expect(text).toContain('Mode: Compare');
    expect(text).toContain('Metric: Damage');
    expect(text).toContain('1. Alice: 1,234');
  });

  it('localizes date and unknown formatting based on current language', async () => {
    await i18next.changeLanguage('zh-CN');

    const zhSnapshot = generateAnalyticsSnapshot('compare', 'damage', [], { members: [] });
    expect(zhSnapshot).toContain('公会战分析快照');
    expect(zhSnapshot).not.toContain('War Analytics Snapshot');
    expect(zhSnapshot).toContain('未知');

    expect(formatWarDate('invalid-date')).toBe('未知');
    expect(formatPercentage(null)).toBe('未知');
    expect(formatLargeNumber(null)).toBe('未知');
  });
});
